export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "black": "#000000",
        "graphite": "#4D4D4D",
        "light-gray": "#C9C9C9",
        "orange-red": "#FF3600",
        "on-background": "#e3e2e2",
        "inverse-surface": "#e3e2e2",
        "primary-fixed-dim": "#FF3600",
        "surface-tint": "#FF3600",
        "primary-fixed": "#FF3600",
        "on-secondary-fixed": "#201c00",
        "secondary-fixed-dim": "#dbc900",
        "on-tertiary": "#303030",
        "on-error-container": "#ffdad6",
        "on-surface": "#e3e2e2",
        "surface-dim": "#121414",
        "surface-container-high": "#292a2a",
        "inverse-on-surface": "#2f3131",
        "surface-container": "#1e2020",
        "primary": "#FF3600",
        "outline-variant": "#4D4D4D",
        "on-secondary": "#363100",
        "surface-container-highest": "#333535",
        "on-tertiary-fixed": "#1b1c1c",
        "error": "#ffb4ab",
        "tertiary-fixed": "#e4e2e2",
        "inverse-primary": "#FF3600",
        "surface-container-lowest": "#0d0e0f",
        "on-primary-fixed": "#ffffff",
        "on-tertiary-container": "#292a2a",
        "primary-container": "#FF3600",
        "on-secondary-fixed-variant": "#4f4800",
        "secondary-container": "#fae500",
        "on-error": "#690005",
        "tertiary-container": "#919090",
        "on-surface-variant": "#C9C9C9",
        "background": "#121414",
        "secondary-fixed": "#fae500",
        "on-primary": "#ffffff",
        "tertiary": "#c8c6c6",
        "on-secondary-container": "#6f6500",
        "secondary": "#ffffff",
        "surface-bright": "#38393a",
        "surface-variant": "#333535",
        "outline": "#C9C9C9",
        "error-container": "#93000a",
        "surface-container-low": "#1a1c1c",
        "on-primary-fixed-variant": "#ffffff",
        "surface": "#121414",
        "on-tertiary-fixed-variant": "#474747",
        "on-primary-container": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "gutter": "24px",
        "sm": "12px",
        "margin": "clamp(16px, 5vw, 40px)",
        "xl": "clamp(48px, 9vw, 80px)",
        "lg": "clamp(28px, 6vw, 48px)",
        "md": "clamp(18px, 5vw, 24px)",
        "base": "8px"
      },
      fontFamily: {
        "label-bold": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
        "body-md": ["Inter"],
        "mono-data": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "headline-lg": ["Space Grotesk"]
      },
      fontSize: {
        "label-bold": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-xl": ["clamp(42px, 11vw, 64px)", { "lineHeight": "1.08", "letterSpacing": "0", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "mono-data": ["14px", { "lineHeight": "1.0", "fontWeight": "400" }],
        "headline-md": ["clamp(18px, 4.8vw, 20px)", { "lineHeight": "1.1", "fontWeight": "500" }],
        "body-lg": ["clamp(16px, 4.3vw, 18px)", { "lineHeight": "1.55", "fontWeight": "400", "letterSpacing": "0.02em"}],
        "headline-lg": ["clamp(30px, 8vw, 40px)", { "lineHeight": "1.12", "letterSpacing": "0", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
